name: Build_SGSI

on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env

      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.rom_url }}" "ROM_URL config"
          required "${{ steps.config.outputs.build_type }}" "BUILD_TYPE config"
          required "${{ steps.config.outputs.os_type }}" "OS_TYPE config"
          required "${{ steps.config.outputs.zip_name }}" "ZIP_NAME config"
          required "${{ steps.config.outputs.version }}" "VERSION config"
          required "${{ steps.config.outputs.repack_name }}" "REPACK_NAME config"

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set swap to 5G
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Setup Environment
        run: |
          sudo apt-get install -y git wget git zip unzip curl axel

      - name: Cloning SGSI
        run: |
          git clone --recurse-submodules https://github.com/xiaoxindada/SGSI-build-tool.git -b 12 $GITHUB_WORKSPACE/SGSI-build-tool
    
